package dev.akshith;

import dev.akshith.model.User;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 * Akshith Ragukumar hotel management login page CSIS 505
 *
 * @author Akshith
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Email = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        jTxtUsername = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jButtonLogiin = new javax.swing.JButton();
        JButtonSupport = new javax.swing.JButton();
        jPanelHotelName = new javax.swing.JPanel();
        jLabelHotelName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Email.setText("Username:");

        Password.setText("Password:");

        jButtonLogiin.setBackground(new java.awt.Color(0, 102, 153));
        jButtonLogiin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogiin.setText("Login");
        jButtonLogiin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogiinActionPerformed(evt);
            }
        });

        JButtonSupport.setBackground(new java.awt.Color(0, 102, 153));
        JButtonSupport.setForeground(new java.awt.Color(255, 255, 255));
        JButtonSupport.setText("Support");
        JButtonSupport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonSupportActionPerformed(evt);
            }
        });

        jPanelHotelName.setBackground(new java.awt.Color(0, 102, 153));
        jPanelHotelName.setPreferredSize(new java.awt.Dimension(100, 100));

        jLabelHotelName.setBackground(new java.awt.Color(255, 255, 255));
        jLabelHotelName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelHotelName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHotelName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHotelName.setText("Akshith Ragukumar Hotel");

        javax.swing.GroupLayout jPanelHotelNameLayout = new javax.swing.GroupLayout(jPanelHotelName);
        jPanelHotelName.setLayout(jPanelHotelNameLayout);
        jPanelHotelNameLayout.setHorizontalGroup(
            jPanelHotelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHotelNameLayout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jLabelHotelName)
                .addContainerGap(265, Short.MAX_VALUE))
        );
        jPanelHotelNameLayout.setVerticalGroup(
            jPanelHotelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHotelNameLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabelHotelName)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHotelName, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JButtonSupport)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Password)
                                    .addComponent(Email))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTxtUsername)
                                    .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButtonLogiin))
                        .addGap(139, 139, 139))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelHotelName, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Email)
                    .addComponent(jTxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password)
                    .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jButtonLogiin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(JButtonSupport)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogiinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogiinActionPerformed
        // Retrieve the email and password entered by the user
        String email = jTxtUsername.getText();
        String password = new String(jPassword.getPassword());
        User user = new User();
        user.setEmail(email);
        user.setPassword(password);
        // Query to check if a user with the entered email and password exists
        String query = "SELECT * FROM Users WHERE email = ? AND password = ?";
        try (Connection connection = DatabaseConnection.connect(); PreparedStatement stmt = connection.prepareStatement(query)) {
            stmt.setString(1, user.getEmail());
            stmt.setString(2, user.getPassword());

            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
                user.setUserType(rs.getString("user_type"));
                user.setUserId(rs.getInt("USER_ID"));
                if ("Admin".equals(user.getUserType())) {
                    new AdminPage().setVisible(true);
                } else {
                    UserPage userPage = new UserPage();
                    userPage.jLabelEmail.setText(user.getEmail());
                    userPage.jLabelUserId.setText(String.valueOf(user.getUserId()));
                    userPage.jLabelUserId.setVisible(false);
                    userPage.setVisible(true);
                }
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Invalid credentials. Try again.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }

    }//GEN-LAST:event_jButtonLogiinActionPerformed

    private void JButtonSupportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonSupportActionPerformed
        new SupportPage().setVisible(true); // Reload SupportPage
        this.dispose();
    }//GEN-LAST:event_JButtonSupportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Email;
    private javax.swing.JButton JButtonSupport;
    private javax.swing.JLabel Password;
    private javax.swing.JButton jButtonLogiin;
    private javax.swing.JLabel jLabelHotelName;
    private javax.swing.JPanel jPanelHotelName;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jTxtUsername;
    // End of variables declaration//GEN-END:variables
}
