package dev.akshith;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import dev.akshith.model.Review;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;

/**
 * Akshith Ragukumar hotel management Review page CSIS 505
 *
 * @author Akshith
 */
public class ReviewPage extends javax.swing.JFrame {

    /**
     * Creates new form ReviewPage
     */
    public ReviewPage() {
        initComponents();
        selectRoomComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Standard", "Deluxe", "Luxury"}));
        jLabelEmail.setVisible(false);
        jLabelUserId.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHotelName = new javax.swing.JPanel();
        jLabelHotelName = new javax.swing.JLabel();
        jPanelReview = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaMessage = new javax.swing.JTextArea();
        jLabelWriteReview = new javax.swing.JLabel();
        jButtonSubmit = new javax.swing.JButton();
        selectRoomComboBox = new javax.swing.JComboBox<>();
        jLabelConfirmation = new javax.swing.JLabel();
        jButtonHome = new javax.swing.JButton();
        jButtonSupport = new javax.swing.JButton();
        jButtonWriteReview = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jLabelUserId = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelHotelName.setBackground(new java.awt.Color(0, 102, 153));

        jLabelHotelName.setBackground(new java.awt.Color(255, 255, 255));
        jLabelHotelName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelHotelName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHotelName.setText("Akshith Ragukumar Hotel");

        javax.swing.GroupLayout jPanelHotelNameLayout = new javax.swing.GroupLayout(jPanelHotelName);
        jPanelHotelName.setLayout(jPanelHotelNameLayout);
        jPanelHotelNameLayout.setHorizontalGroup(
            jPanelHotelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHotelNameLayout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jLabelHotelName)
                .addContainerGap(265, Short.MAX_VALUE))
        );
        jPanelHotelNameLayout.setVerticalGroup(
            jPanelHotelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHotelNameLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelHotelName)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanelReview.setBackground(new java.awt.Color(153, 153, 153));

        jTextAreaMessage.setColumns(20);
        jTextAreaMessage.setLineWrap(true);
        jTextAreaMessage.setRows(5);
        jTextAreaMessage.setText("Write your review");
        jTextAreaMessage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(jTextAreaMessage);

        jLabelWriteReview.setText("Write a Review");

        jButtonSubmit.setBackground(new java.awt.Color(0, 102, 153));
        jButtonSubmit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSubmit.setText("Submit");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });

        selectRoomComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanelReviewLayout = new javax.swing.GroupLayout(jPanelReview);
        jPanelReview.setLayout(jPanelReviewLayout);
        jPanelReviewLayout.setHorizontalGroup(
            jPanelReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelReviewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelReviewLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelWriteReview)
                    .addComponent(selectRoomComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114))
            .addGroup(jPanelReviewLayout.createSequentialGroup()
                .addGroup(jPanelReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelReviewLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jButtonSubmit))
                    .addGroup(jPanelReviewLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabelConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelReviewLayout.setVerticalGroup(
            jPanelReviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReviewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWriteReview)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectRoomComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSubmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelConfirmation, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonHome.setBackground(new java.awt.Color(0, 102, 153));
        jButtonHome.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHome.setText("Home");
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        jButtonSupport.setBackground(new java.awt.Color(0, 102, 153));
        jButtonSupport.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSupport.setText("Support");
        jButtonSupport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupportActionPerformed(evt);
            }
        });

        jButtonWriteReview.setBackground(new java.awt.Color(0, 102, 153));
        jButtonWriteReview.setForeground(new java.awt.Color(255, 255, 255));
        jButtonWriteReview.setText("Write a Review");
        jButtonWriteReview.setEnabled(false);
        jButtonWriteReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWriteReviewActionPerformed(evt);
            }
        });

        jButtonLogout.setBackground(new java.awt.Color(0, 102, 153));
        jButtonLogout.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHotelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSupport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonWriteReview)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonLogout)
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelReview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(242, 242, 242))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelHotelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonHome)
                            .addComponent(jButtonSupport)
                            .addComponent(jButtonWriteReview)
                            .addComponent(jButtonLogout)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jPanelReview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        UserPage userPage = new UserPage();
        userPage.jLabelUserId.setText(jLabelUserId.getText());
        userPage.jLabelEmail.setText(jLabelEmail.getText());
        userPage.setVisible(true); // Navigate to HomePage
        this.dispose();
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonSupportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupportActionPerformed
        SupportPage supportPage = new SupportPage();
        supportPage.jLabelUserId.setText(jLabelUserId.getText());
        supportPage.jLabelEmail.setText(jLabelEmail.getText());
        supportPage.setVisible(true); // Reload SupportPage
        this.dispose();
    }//GEN-LAST:event_jButtonSupportActionPerformed

    private void jButtonWriteReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWriteReviewActionPerformed
        new ReviewPage().setVisible(true); // Navigate to ReviewPage
        this.dispose();
    }//GEN-LAST:event_jButtonWriteReviewActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        new LoginPage().setVisible(true); // Navigate to LoginPage
        this.dispose();
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        Review review = new Review();
        // User's userId
        review.setUserId(Integer.parseInt(jLabelUserId.getText()));
        review.setRoomId(selectRoomComboBox.getSelectedIndex() + 1);
        // Review message
        review.setComment(jTextAreaMessage.getText());    

        // Validate input fields
        if (review.getUserId() <= 0 || review.getRoomId() <= 0 || review.getComment().isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields are required.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Database query to insert the review
        String query = "INSERT INTO Reviews (USER_ID, ROOM_ID, COMMENT) VALUES (?, ?, ?)";

        jLabelConfirmation.setText("");
        try (Connection connection = DatabaseConnection.connect()) {
            PreparedStatement stmt = connection.prepareStatement(query);
            stmt.setInt(1, review.getUserId());
            stmt.setInt(2, review.getRoomId());
            stmt.setString(3, review.getComment());

            int rows = stmt.executeUpdate();
            String confirmationMessage;
            if (rows > 0) {
                confirmationMessage = "Review submitted successfully!";
                // Clear fields                
                jTextAreaMessage.setText("");
                selectRoomComboBox.setSelectedIndex(0);
            } else {
                confirmationMessage = "Failed to submit the review.";
            }
            jLabelConfirmation.setText(confirmationMessage);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReviewPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReviewPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReviewPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReviewPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReviewPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JButton jButtonSupport;
    private javax.swing.JButton jButtonWriteReview;
    private javax.swing.JLabel jLabelConfirmation;
    public javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelHotelName;
    public javax.swing.JLabel jLabelUserId;
    private javax.swing.JLabel jLabelWriteReview;
    private javax.swing.JPanel jPanelHotelName;
    private javax.swing.JPanel jPanelReview;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaMessage;
    private javax.swing.JComboBox<String> selectRoomComboBox;
    // End of variables declaration//GEN-END:variables
}
