package dev.akshith;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import dev.akshith.model.SupportTicket;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;

/**
 * Akshith Ragukumar hotel management Support page CSIS 505
 *
 * @author Akshith
 */
public class SupportPage extends javax.swing.JFrame {

    /**
     * Creates new form SupportFrame
     */
    public SupportPage() {
        initComponents();
        jLabelEmail.setVisible(false);
        jLabelUserId.setVisible(false);

        jTextFieldName.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (jTextFieldName.getText().equals("Name")) {
                    jTextFieldName.setText(""); // Clear placeholder text
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (jTextFieldName.getText().isEmpty()) {
                    jTextFieldName.setText("Name"); // Restore placeholder text
                }
            }
        });

        jTextFieldEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (jTextFieldEmail.getText().equals("Email")) {
                    jTextFieldEmail.setText(""); // Clear placeholder text
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (jTextFieldEmail.getText().isEmpty()) {
                    jTextFieldEmail.setText("Email"); // Restore placeholder text
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHotelName = new javax.swing.JPanel();
        jLabelHotelName = new javax.swing.JLabel();
        jPanelSupport = new javax.swing.JPanel();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaTitle = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButtonSubmit = new javax.swing.JButton();
        jLabelConfirmation = new javax.swing.JLabel();
        jButtonHome = new javax.swing.JButton();
        jButtonSupport = new javax.swing.JButton();
        jButtonWriteReview = new javax.swing.JButton();
        jButtonLogout = new javax.swing.JButton();
        jLabelUserId = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelHotelName.setBackground(new java.awt.Color(0, 102, 153));

        jLabelHotelName.setBackground(new java.awt.Color(255, 255, 255));
        jLabelHotelName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelHotelName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHotelName.setText("Akshith Ragukumar Hotel");

        javax.swing.GroupLayout jPanelHotelNameLayout = new javax.swing.GroupLayout(jPanelHotelName);
        jPanelHotelName.setLayout(jPanelHotelNameLayout);
        jPanelHotelNameLayout.setHorizontalGroup(
            jPanelHotelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHotelNameLayout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jLabelHotelName)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelHotelNameLayout.setVerticalGroup(
            jPanelHotelNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHotelNameLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelHotelName)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanelSupport.setBackground(new java.awt.Color(153, 153, 153));

        jTextFieldName.setBackground(new java.awt.Color(194, 223, 253));
        jTextFieldName.setText("Name");

        jTextFieldEmail.setBackground(new java.awt.Color(194, 223, 253));
        jTextFieldEmail.setText("Email");

        jTextAreaTitle.setColumns(20);
        jTextAreaTitle.setLineWrap(true);
        jTextAreaTitle.setRows(5);
        jTextAreaTitle.setText("Type your message");
        jTextAreaTitle.setToolTipText("");
        jTextAreaTitle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(jTextAreaTitle);

        jLabel1.setText("Support");

        jButtonSubmit.setBackground(new java.awt.Color(0, 102, 153));
        jButtonSubmit.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSubmit.setText("Submit");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSupportLayout = new javax.swing.GroupLayout(jPanelSupport);
        jPanelSupport.setLayout(jPanelSupportLayout);
        jPanelSupportLayout.setHorizontalGroup(
            jPanelSupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSupportLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelSupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSupportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanelSupportLayout.createSequentialGroup()
                .addGroup(jPanelSupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSupportLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1))
                    .addGroup(jPanelSupportLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jButtonSubmit))
                    .addGroup(jPanelSupportLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jLabelConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelSupportLayout.setVerticalGroup(
            jPanelSupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSupportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSubmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelConfirmation, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jButtonHome.setBackground(new java.awt.Color(0, 102, 153));
        jButtonHome.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHome.setText("Home");
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        jButtonSupport.setBackground(new java.awt.Color(0, 102, 153));
        jButtonSupport.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSupport.setText("Support");
        jButtonSupport.setEnabled(false);
        jButtonSupport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupportActionPerformed(evt);
            }
        });

        jButtonWriteReview.setBackground(new java.awt.Color(0, 102, 153));
        jButtonWriteReview.setForeground(new java.awt.Color(255, 255, 255));
        jButtonWriteReview.setText("Write a Review");
        jButtonWriteReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonWriteReviewActionPerformed(evt);
            }
        });

        jButtonLogout.setBackground(new java.awt.Color(0, 102, 153));
        jButtonLogout.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHotelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jPanelSupport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonHome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSupport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonWriteReview)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jButtonLogout)
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelHotelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonHome)
                                .addComponent(jButtonSupport)
                                .addComponent(jButtonWriteReview)
                                .addComponent(jButtonLogout))
                            .addComponent(jLabelUserId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jPanelSupport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        UserPage userPage = new UserPage();
        userPage.jLabelUserId.setText(jLabelUserId.getText());
        userPage.jLabelEmail.setText(jLabelEmail.getText());
        userPage.setVisible(true); // Navigate to HomePage
        this.dispose();
    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonSupportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupportActionPerformed
        new SupportPage().setVisible(true); // Reload SupportPage
        this.dispose();
    }//GEN-LAST:event_jButtonSupportActionPerformed

    private void jButtonWriteReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonWriteReviewActionPerformed
        ReviewPage reviewPage = new ReviewPage();
        reviewPage.jLabelUserId.setText(jLabelUserId.getText());
        reviewPage.jLabelEmail.setText(jLabelEmail.getText());
        reviewPage.setVisible(true); // Navigate to ReviewPage
        this.dispose();
    }//GEN-LAST:event_jButtonWriteReviewActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        new LoginPage().setVisible(true); // Navigate to LoginPage
        this.dispose();
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        SupportTicket supportTicket = new SupportTicket();
        supportTicket.setName(jTextFieldName.getText());
        supportTicket.setEmail(jTextFieldEmail.getText());
        supportTicket.setTitle(jTextAreaTitle.getText());

        // Validate input fields
        if (supportTicket.getName().isEmpty() || supportTicket.getEmail().isEmpty() || supportTicket.getTitle().isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields are required.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Insert query for support tickets
        String query = "INSERT INTO Support_Tickets (NAME, EMAIL, TITLE, STATUS) VALUES (?, ?, ?, 'Open')";

        jLabelConfirmation.setText("");
        try (Connection connection = DatabaseConnection.connect(); PreparedStatement stmt = connection.prepareStatement(query)) {
            // Set parameters
            stmt.setString(1, supportTicket.getName());
            stmt.setString(2, supportTicket.getEmail());
            stmt.setString(3, supportTicket.getTitle());

            // Execute the query
            int rows = stmt.executeUpdate();
            if (rows > 0) {
                jLabelConfirmation.setText("Ticket Submitted.");
                // Clear input fields
                jTextFieldName.setText("");
                jTextFieldEmail.setText("");
                jTextAreaTitle.setText("");
            } else {
                jLabelConfirmation.setText("Ticket submission failed.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupportPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupportPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupportPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupportPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupportPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JButton jButtonSupport;
    private javax.swing.JButton jButtonWriteReview;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelConfirmation;
    public javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelHotelName;
    public javax.swing.JLabel jLabelUserId;
    private javax.swing.JPanel jPanelHotelName;
    private javax.swing.JPanel jPanelSupport;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaTitle;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables
}
